language: rust

rust: [stable, beta, nightly]

env:
  - FEATURES=''
  - FEATURES='--no-default-features'

install: cargo build --verbose --all-targets $FEATURES

script:
  - cargo test --verbose $FEATURES
  - cargo run --verbose $FEATURES --example builders
  - '[ "$FEATURES" != "--no-default-features" ] && cargo run --verbose $FEATURES --example client || true'
